### ISSUE TITLE
Setup kanbanboard ready for review

### ISSUE THREAD

**Issue by ahmetbozaci** [ahmetbozaci/recovon-backend#25]
We are 3 people on the team.

[Back-end repository](https://github.com/ahmetbozaci/final-project-backend)
[Front-end repository](https://github.com/ahmetbozaci/final-project-frontend)
[Kanbanboard](https://github.com/ahmetbozaci/final-project-backend/projects/1)

![image](https://user-images.githubusercontent.com/38635158/155567392-c34ed198-7877-4e6c-8ab6-71b0310416ca.png)

**Comment by MuriloRoque** [comment]
Hi @ahmetbozaci, @aliabbani, @tufoinnkuo10,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
